# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# An example API configuration.
#
# Below, replace MY_PROJECT_ID with your Google Cloud Project ID.
#

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: grpc-demo.endpoints.technical-services-dev.cloud.goog

#
# Configuring DNS
#
endpoints:
  - name: grpc-demo.endpoints.technical-services-dev.cloud.goog
    target: 35.238.30.139

#
# API title to appear in the user interface (Google Cloud Console).
#
title: gRPC Demo
apis:
  - name: PingPongService

#
# HTTP rules define translation from HTTP/REST/JSON to gRPC. With these rules
# HTTP/REST/JSON clients will be able to call the Bookstore service.
#
http:
  rules:
    #
    # HTTP/REST/JSON clients can call the 'Ping' method of the PingPongService
    # using the POST HTTP verb and the '/ping' URL path.
    # The posted HTTP body is the JSON respresentation of the
    # Ping protobuf message. The response
    # will be the JSON representation of the 'Pong' message.
    #
    - selector: PingPongService.PingPong
      get: /pingpong/{ping}
    #
    # HTTP/REST/JSON clients can call the 'Ping' method of the PingPongService
    # using the POST HTTP verb and the '/pingPong' URL path.
    # The posted HTTP body is the repeated JSON respresentation of the
    # Ping protobuf message. The response
    # will be the repeated JSON representation of the 'Pong' message.
    #
    - selector: PingPongService.PingPongStream
      post: /pingpong/stream
      body: "*"

#
# API usage restrictions
#
usage:
  rules:
    # None of these API methods require an API key
    # N.B: JWTs are not a substitute for API keys
    - selector: "*"
      allow_unregistered_calls: true
