{{- if .Values.gateway.enabled -}}
{{- $fullName := include "grpc-demo.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 50051
      name: grpc
      protocol: GRPC
    hosts:
      - "*"
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-endpoint-virtual-svc
spec:
  hosts:
  - {{ .Values.deploy.esp.args.service }}
  gateways:
  - {{ .Values.istio.gateway.name }}.{{ .Values.istio.gateway.namespace }}.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /pingpong
    route:
    - destination:
        host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-virtual-svc
spec:
  hosts:
    - "*"
  gateways:
    - {{ $fullName }}-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 50051
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $fullName }}-destination-rule
spec:
  host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- end }}